name: uptodo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  easy_date_timeline: ^2.0.6
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  contained_tab_bar_view: ^0.8.0
  fluttertoast: ^8.2.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  table_calendar: ^3.1.3
  numberpicker: ^2.1.2
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  persistent_bottom_nav_bar: ^6.2.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.3.0
  flutter_timezone: ^4.1.1
  timezone: ^0.10.1
  workmanager: ^0.8.0
  device_info_plus: ^11.2.0
  flutter_settings_ui: ^3.0.1
  crypto: ^3.0.6
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.8.0
  meta: ^1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0


flutter:
  generate: true

  uses-material-design: true

  assets:
    - Assets/Images/


